Adding support for `.ejs` files
CloudCannon/bookshop pull request #16
Opened 2020-12-15 21:55 UTC by Robbie-Cook

Also fixes [#15 ],[#14 ]

2020-12-15 21:56 UTC, Robbie-Cook commented on examples/example-bookshop/package.json
> +    "@bookshop/ejs-engine": "file:../../engines/ejs-engine",
This needs to be linked directly to the package when the package exists

2020-12-15 21:57 UTC, Robbie-Cook commented on loader/package.json
> +    "@bookshop/ejs-engine": "file:../engines/ejs-engine",
This also needs to be directly linked to the package when it exists

2020-12-15 21:59 UTC, Robbie-Cook commented
@bglw

2020-12-15 22:20 UTC, bglw requested changes
It would be great if we can avoid having to transpile this engine.

If you include the client build (https://npmcdn.com/ejs@3.1.5/ejs.js) then we can run it in the browser without any transpilation. I don't think there's an npm module with the client build, but that file looks requirable if it were dropped in. 

You'll also need to add support for includes inside ejs files. You can see how to handle includes on their Github: https://github.com/mde/ejs#caveats

So on catching an include you'll need to do the network request to get a file and return it (similar to underscore-engine behaviour)

2020-12-15 22:32 UTC, Robbie-Cook commented
Great! Thank you for your review!

> It would be great if we can avoid having to transpile this engine.
> 
> If you include the client build ([npmcdn.com/ejs@3.1.5/ejs.js](https://npmcdn.com/ejs@3.1.5/ejs.js)) then we can run it in the browser without any transpilation. I don't think there's an npm module with the client build, but that file looks requirable if it were dropped in.

I'll do this.

However, I think this is potentially problematic. Transpiling allows us to keep up to date with the latest `ejs` package, but maunally copying a script so `require` will work natively makes it harder to update. 

There are also other advantages of transpiling (e.g. ES2020 support for older node LTS versions) which I am sure you are aware of.

> 
> You'll also need to add support for includes inside ejs files. You can see how to handle includes on their Github: [mde/ejs#caveats](https://github.com/mde/ejs#caveats)

> 
> So on catching an include you'll need to do the network request to get a file and return it (similar to underscore-engine behaviour)

Great! Thanks for this. I will start adding this now. Good catch!

2020-12-15 22:38 UTC, bglw commented
> Great! Thank you for your review @bglw !
> 
> > It would be great if we can avoid having to transpile this engine.
> > If you include the client build ([npmcdn.com/ejs@3.1.5/ejs.js](https://npmcdn.com/ejs@3.1.5/ejs.js)) then we can run it in the browser without any transpilation. I don't think there's an npm module with the client build, but that file looks requirable if it were dropped in.
> 
> I'll do this.
> 
> However, I think this is potentially problematic. Transpiling allows us to keep up to date with the latest `ejs` package, but maunally copying a script so `require` will work natively makes it harder to update.
> 
> There are also other advantages of transpiling (e.g. ES2020 support for older node LTS versions) which I am sure you are aware of.

Let's do this more problematic way for now, just so we don't have to deal with transpilation for the bookshop refactor that's in the pipes. After that, we can revisit this setup.
> 
> > You'll also need to add support for includes inside ejs files. You can see how to handle includes on their Github: [mde/ejs#caveats](https://github.com/mde/ejs#caveats)
> 
> > So on catching an include you'll need to do the network request to get a file and return it (similar to underscore-engine behaviour)
> 
> Great! Thanks for this. I will start adding this now. Good catch!
🤙

2020-12-16 00:41 UTC, Robbie-Cook commented
Hey @bglw , have removed webpack.

Just working on the `include` behaviour now :)

2020-12-20 21:12 UTC, Robbie-Cook commented
Hey @bglw , includes now work in storybook! 

The syntax matches the `ejs` spec e.g. `include('components/button/button.ejs', { props: { text: props.text, type } });`, 

This should be good to go, I think!

2020-12-20 21:39 UTC, Robbie-Cook commented
Also, cleaned up the diff a bit by undoing my prettier format, so should be nicer to read

2020-12-20 21:40 UTC, Robbie-Cook commented on loader/src/index.js
> +  data.defaults = {
This fixes #14

2020-12-20 21:41 UTC, Robbie-Cook commented on engines/ejs-engine/src/ejs.js
> +(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=wi
You can ignore this file -- it is the ejs browsified renderer

2020-12-20 22:23 UTC, bglw reviewed
- Just checking - you access variables through a key `props`? So you would expect `<%= include.text %>` rather than `<%= text %>`
- Curious about the decision to override the include variable rather than using the [include callback](https://github.com/mde/ejs#caveats) feature ejs has?
- If you do intend to use the override instead, looks like you will also need to provide it in an included file. Looking at it I don't think including a file that includes a file will work as is.

2020-12-21 01:38 UTC, Robbie-Cook commented
Thanks @bglw 

> * Just checking - you access variables through a key `props`? So you would expect `<%= include.text %>` rather than `<%= text %>`

I think that you don't necessarily need to key the passed data to `props` - this is just mapped from the storybook loader render function (operates the same as your `underscore` engine). Here is the syntax for an include in a `.ejs` file: 

![image](https://user-images.githubusercontent.com/13477291/102730336-444ebc00-4399-11eb-9167-19a4c06382be.png)

> * Curious about the decision to override the include variable rather than using the [include callback](https://github.com/mde/ejs#caveats) feature ejs has?

> * If you do intend to use the override instead, looks like you will also need to provide it in an included file. Looking at it I don't think including a file that includes a file will work as is.

As is, including a file that includes a file seems to be working fine.
Here is an example of a file that includes a button component, and the button component includes an input component i.e.:

overview
	-> button.ejs
		-> filter.ejs

: 

![image](https://user-images.githubusercontent.com/13477291/102730461-ba532300-4399-11eb-947d-3f9fce2999f7.png)

Is this okay? The current solution was just the easiest one, and it seems to work fine for the storybook. 
Ofc, the loader for the app will have to be different

2020-12-21 02:03 UTC, bglw approved these changes
Cool, looks good then

2020-12-21 22:40 UTC, Robbie-Cook commented
@bglw We've decided to make the `props` the only data passed in, so the new syntax for importing will be:

```ejs
<%- include('components/button/button.ejs', { text: props.text, type }); %>
```.

It is not as general as it could be, the benefits are component consistency and succintness

2021-01-04 21:42 UTC, merged